language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - touch .env
  - docker-compose up autotests
  - docker-compose run autotests coverage report
  - docker-compose run autotests coverage xml

after_success:
  - sudo pip install codacy-coverage==1.3.11
  - python-codacy-coverage -r ./coverage.xml
