language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - touch .env
  - docker-compose build
  - docker-compose up -d db_java_wallet
  - docker-compose run service ./manage.py test -v2
