language: minimal

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - touch .env
  - docker-compose build
  - docker-compose up -d db_java_wallet
  - docker-compose run service ./manage.py test -v2 --with-coverage
#  - docker-compose run service coverage report
#  - docker-compose run service coverage xml

after_success:
  - sudo pip install codacy-coverage==1.3.11
  - python-codacy-coverage -r ./coverage.xml
