version: '3'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8301:8301"
    volumes:
      - .:/app
    environment:
      DJANGO_MIGRATE: "on"
      START_SERVER: "on"
    env_file:
      - .env
