version: '3'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env

  autotests:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "test", "-v2", "--no-input"]
    volumes:
      - .:/code
    env_file:
      - .env
